### PR TITLE
Fix a few memory management related issues

### LINKED ISSUE #589: Invalid read of size 4. Address sanity check failed.
```
==26900==ERROR: AddressSanitizer: heap-use-after-free on address 0x61400000e720 at pc 0xbc5057 bp 0x7f870c2bd510 sp 0x7f870c2bd508
READ of size 4 at 0x61400000e720 thread T0
    #0 0xbc5056 in ocf_core_seq_cutoff_update fs/cache/ocf_cache/ocf/src/ocf_seq_cutoff.c:309
    #1 0xbc7f97 in ocf_core_volume_submit_io fs/cache/ocf_cache/ocf/src/ocf_core.c:299
    #2 0xbca2db in ocf_volume_submit_io fs/cache/ocf_cache/ocf/src/ocf_volume.c:269
    #3 0x9a2667 in ocf_core_submit_io fs/cache/ocf_cache/include/ocf/ocf_core.h:169
```

```C++
void ocf_core_seq_cutoff_update(ocf_core_t core, struct ocf_request *req)
{
        // ...
	if (req->byte_length >= threshold)
		promote = true;
```

### PR DESCRIPTION
**Pull request by mmichal10**
Closes #589

### CODE REVIEW

**Review by robertbaldyga — DISMISSED** [review]

File: src/metadata/metadata_raw_dynamic.c [hunk 1]
```diff
@@ -332,6 +332,8 @@ int raw_dynamic_update(ocf_cache_t cache,
 * RAM DYNAMIC Implementation - Load all
 */
 #define RAW_DYNAMIC_LOAD_PAGES 128
+#define metadata_io_size(__i_page, __page_max) \
+	PAGES_TO_BYTES(OCF_MIN(RAW_DYNAMIC_LOAD_PAGES, (__page_max -__i_page)))
```
Comment (robertbaldyga) [inline src/metadata/metadata_raw_dynamic.c:336]: I'd rename `__page_max` to `__pages_total`.

**Review by robertbaldyga — APPROVED** [review]

**Review by rafalste — APPROVED** [review]

File: src/ocf_core.c [hunk 2]
```diff
@@ -302,12 +302,16 @@ void ocf_core_volume_submit_io(struct ocf_io *io)
 	ocf_core_update_stats(core, io);
 
 	ocf_io_get(io);
+	/* Prevent race condition */
+	ocf_req_get(req);
```
Comment (beef9999) [inline src/ocf_core.c:307]: Can't believe this part of core code would still have bugs...
