### PR TITLE
simple example: implement queues based on threads

### LINKED ISSUE #564: [example bug] v21.3.3 example code is not working at all
1. The example code in v21.3.3 is not working at all. A floating point exception will occur, because the `ocf_mngt_cache_device_config_set_default` has set a zero cache-line size by default. 

2. Even after setting `device_cfg.cache_line_size = ocf_cache_line_size_default` correctly, the example code will still hang in the final stopping cache step.

3. v20.3.4 is OK

### PR DESCRIPTION
**Pull request by arutk**
Fixes #564 

Signed-off-by: Adam Rutkowski <adam.j.rutkowski@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-cas/ocf/575)

### CODE REVIEW

**Comment by beef9999** [comment]
Which C++ version does it require, 20 ?

**Comment by beef9999** [comment]
I was thinking to suggest pure async C libraries like State Threads, but indeed C++11 threads is a much better solution as a sample code.

Splendid.

**Comment by arutk** [comment]
Hi @beef9999. Thanks for your feedback. Unfortunately after some more consideration I have realized, that mixing pthread usage with c++ threads is potentially unsafe. And our OCF enviromnent for the sample is based on the pthread. So I should probably change this PR to use pthreads instead of c++ standard library :(.

**Comment by arutk** [comment]
@beef9999 sure, I was about to debug your POC. will let you know

**Review by beef9999 — APPROVED** [review]

File: example/simple/src/queue_thread.cpp [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+{
+	int ret = 0;
+
+	try {
+		struct queue_thread* mngt_queue_thread = new queue_thread(mngt_queue);
+		struct queue_thread* io_queue_thread = new queue_thread(io_queue);
+
+		ocf_queue_set_priv(mngt_queue, mngt_queue_thread);
+		ocf_queue_set_priv(io_queue, io_queue_thread);
+	} catch(...) {
```
Comment (kmajzero) [inline example/simple/src/queue_thread.cpp:70]: Pokemon-style exception handling does not look good. How about "catch(std::bad_alloc)"  ;) ?

Comment (arutk) [reply example/simple/src/queue_thread.cpp:70]: I have changed implementation to C

File: example/simple/src/queue_thread.c [hunk 2]
```diff
@@ -0,0 +1,152 @@
...
+			qt->signalled = false;
+			pthread_mutex_unlock(&qt->mutex);
+
+			/* execute items on the queue */
+			ocf_queue_run(q);
+
+			pthread_mutex_lock(&qt->mutex);
+		}
+
+		pthread_cond_wait(&qt->cv, &qt->mutex);
```
[the remark this answers is not in the document]
Comment (arutk) [reply example/simple/src/queue_thread.c:110]: looks like wait is unnecessary in this case

File: example/simple/src/main.c [hunk 3]
```diff
@@ -157,8 +141,13 @@ int initialize_cache(ocf_ctx_t ctx, ocf_cache_t *cache)
...
 
+	ret = initialize_threads(cache_priv->mngt_queue, cache_priv->io_queue);
+	if (ret)
+		goto err_cache;
+
 	/* Attach volume to cache */
 	ocf_mngt_cache_attach(*cache, &device_cfg, simple_complete, &context);
+	sem_wait(&context.sem);
 	if (ret)
 		goto err_cache;
```
[the remark this answers is not in the document]
Comment (arutk) [reply example/simple/src/main.c:152]: ret is referenced via pointer in simple_complete :O

File: example/simple/src/queue_thread.c [hunk 4]
```diff
@@ -0,0 +1,152 @@
...
+
+			/* execute items on the queue */
+			ocf_queue_run(q);
+
+			pthread_mutex_lock(&qt->mutex);
+		}
+
+		if (!qt->stop)
+			pthread_cond_wait(&qt->cv, &qt->mutex);
+	} while (!qt->stop);
```
Comment (rafalste) [inline example/simple/src/queue_thread.c:111]: Maybe this will do the job:
```
while (!qt->stop && qt->signalled) {
	qt->signalled = false;
	pthread_mutex_unlock(&qt->mutex);

	/* execute items on the queue */
	ocf_queue_run(q);

	pthread_mutex_lock(&qt->mutex);

	pthread_cond_wait(&qt->cv, &qt->mutex);
}
```

Comment (arutk) [reply example/simple/src/queue_thread.c:111]: Looks good. I just needed to add an extra condition before pthread_cond_wait to make sure we don't wait with signalled or stop set.

File: example/simple/src/queue_thread.c [hunk 5]
```diff
@@ -0,0 +1,152 @@
...
+
+			/* execute items on the queue */
+			ocf_queue_run(q);
+
+			pthread_mutex_lock(&qt->mutex);
+		}
+
+		if (!qt->stop && !qt->signalled) 
+			pthread_cond_wait(&qt->cv, &qt->mutex);
+	} while (!qt->stop);
```
Comment (rafalste) [inline example/simple/src/queue_thread.c:111]: Leftover do-while loop condition.

**Review by rafalste — APPROVED** [review]

**Comment by beef9999** [comment]
Can this patch be merged now?

**Comment by beef9999** [comment]
@arutk After some careful thought, I now suspect this queue implementation was done in with a wrong way that has reduced the I/O currency to 1. User may submit I/O concurrently, but this while{} loop with signal notification is not parallel.

I think start a temporary new thread and run ocf_queue_run is just enough.

**Comment by beef9999** [comment]
In my own implementation, I put the condition variable into the `volume_data` and trigger it in `read_complete` or `write_complete`. Looks like it's working and achieved good performance. Don't know if it is flawed.

**Review by rafalste — APPROVED** [review]

**Comment by arutk** [comment]
Hi @beef9999. It is true that the thread loop is not parallelized itself. But this is our intention. Queue is an abstraction for a unit of concurrency. In actual product you would have multiple queues and parallelization would be achieved by running them in parallel.

**Review by kmajzero — APPROVED** [review]
